## Machine learning pipeline 

In [181]:
import numpy as np 
import pandas as pd 

In [182]:
df=pd.read_csv('tested.csv')

In [183]:
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [184]:
df.drop(columns=['PassengerId', 'Name','Ticket','Cabin'],axis=1, inplace=True)

In [185]:
df.isnull().sum()

Survived     0
Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [186]:
df.sample(5)

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Embarked
59          1       1  female  36.0      0      0  262.3750        C
145         0       3    male  31.0      3      0   18.0000        S
181         0       1    male  37.0      1      1   83.1583        C
84          0       2    male   NaN      0      0   10.7083        Q
229         0       2    male  36.0      0      0   13.0000        S

In [187]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.tree import DecisionTreeClassifier

In [188]:
#train test split 
X_train, X_test, y_train,y_test=train_test_split(df.drop(columns=['Survived'],axis=1),df['Survived'],test_size=0.2)

In [189]:
X_train.head()

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
131       1    male  53.0      0      0   28.5000        C
85        3    male   NaN      1      0   14.4542        C
150       1  female  23.0      0      1   83.1583        C
245       1    male  41.0      1      0   51.8625        S
202       1    male  47.0      1      0  227.5250        C

In [190]:
X_train.shape

(334, 7)

In [191]:
X_train.isnull().sum()

Pclass       0
Sex          0
Age         72
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [192]:
si=SimpleImputer()

In [193]:
X_train_age_fare=si.fit_transform(X_train[['Age','Fare']])
X_test_age_fare=si.fit_transform(X_test[['Age','Fare']])

In [194]:
X_train_age_fare.shape

(334, 2)

In [195]:
X_train_age_fare

array([[5.30000000e+01, 2.85000000e+01],
       [3.01908397e+01, 1.44542000e+01],
       [2.30000000e+01, 8.31583000e+01],
       [4.10000000e+01, 5.18625000e+01],
       [4.70000000e+01, 2.27525000e+02],
       [2.00000000e+01, 7.85420000e+00],
       [3.90000000e+01, 1.08900000e+02],
       [3.60000000e+01, 7.52417000e+01],
       [2.10000000e+01, 8.05000000e+00],
       [2.70000000e+01, 8.66250000e+00],
       [3.01908397e+01, 6.43750000e+00],
       [4.70000000e+01, 7.00000000e+00],
       [3.60000000e+01, 3.16792000e+01],
       [3.01908397e+01, 8.05000000e+00],
       [3.30000000e+01, 1.51550000e+02],
       [3.01908397e+01, 3.16833000e+01],
       [4.60000000e+01, 2.60000000e+01],
       [3.01908397e+01, 7.75000000e+00],
       [4.60000000e+01, 7.52417000e+01],
       [3.01908397e+01, 7.89580000e+00],
       [2.40000000e+01, 9.32500000e+00],
       [5.50000000e+01, 5.94000000e+01],
       [2.10000000e+01, 2.41500000e+01],
       [3.70000000e+01, 9.00000000e+01],
       [2.850000

In [196]:
ohe_sex=OneHotEncoder()
ohe_embarked=OneHotEncoder()

In [197]:
X_train_sex=ohe_sex.fit_transform(X_train[['Sex']]).toarray()
X_test_sex=ohe_sex.transform(X_test[['Sex']]).toarray()

In [198]:
X_train_embarked=ohe_embarked.fit_transform(X_train[['Embarked']]).toarray()
X_test_embarked=ohe_embarked.fit_transform(X_test[['Embarked']]).toarray()

In [199]:
X_train_sex.shape, X_train_embarked.shape

((334, 2), (334, 3))

In [200]:
X_train_rem=X_train.drop(columns=['Age','Sex','Embarked','Fare'])
X_test_rem=X_test.drop(columns=['Age','Sex','Embarked','Fare'])

In [201]:
X_train_transformed=np.concatenate((X_train_rem,X_train_age_fare,X_train_sex, X_train_embarked),axis=1)
X_test_transformed=np.concatenate((X_test_rem,X_test_age_fare,X_test_sex, X_test_embarked),axis=1)

In [202]:
X_train_transformed

array([[1., 0., 0., ..., 1., 0., 0.],
       [3., 1., 0., ..., 1., 0., 0.],
       [1., 0., 1., ..., 1., 0., 0.],
       ...,
       [2., 1., 0., ..., 0., 0., 1.],
       [3., 0., 0., ..., 0., 0., 1.],
       [2., 1., 1., ..., 0., 0., 1.]])

In [203]:
X_train_transformed.shape

(334, 10)

In [204]:
X_test_transformed.shape

(84, 10)

In [215]:
clf=DecisionTreeClassifier()

In [216]:
clf.fit(X_train_transformed,y_train)

DecisionTreeClassifier()

In [217]:
y_pred=clf.predict(X_test_transformed)

In [218]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [220]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

1.0